Version: 1.5.0
Installer:
- Architecture: x64
  InstallerUrl: https://cdn.zcode-ai.com/zcode/electron/releases/1.5.0/ZCode-1.5.0-win-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: ""
ReleaseTime: 2026-04-27T16:56:55.0000000Z
