Version: 1.2.1
Installer:
- Architecture: x64
  InstallerUrl: https://cdn.zcode-ai.com/zcode/electron/releases/1.2.1/ZCode-1.2.1-win-x64.exe
Locale:
- Locale: zh-CN
  Key: ReleaseNotes
  Value: ""
ReleaseTime: 2026-04-22T16:13:01.0000000Z
