Version: 2026.4.3
Installer:
- InstallerUrl: https://portswigger-cdn.net/burp/releases/download?product=pro&version=2026.4.3&type=WindowsX64
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: This release fixes a high-impact vulnerability in browser-based crawling on Windows, and a bug affecting custom scan checks.
- Key: ReleaseNotesUrl
  Value: https://portswigger.net/burp/releases/professional-community-2026-4-3
ReleaseTime: 2026-05-13T13:48:00.0000000Z
